apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: collabspace-ingress
  namespace: collabspace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: collabspace.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: server
                port:
                  number: 5000
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: server
                port:
                  number: 5000
